### ISSUE TITLE
Does this work across iframes?

### ISSUE THREAD

**Issue by MattMenke2** [slightlyoff/history_api#15]
I could be missing something, but the spec seems under specified - modal dialogs are generally modal with respect to the tab, not with respect to the frame.  If one frame opens a modal dialog, will parent/child frames receive notifications of the modal being closed?  Seems like this potentially leaks data across site.  If the answer is "no" the spec should make that clear.  If the answer is "yes", the spec should also make that clear.

**Comment by domenic** [comment]
Sorry for missing this; I wasn't subscribed to the repository!

This is entirely about DOM-element "modals", which are frame-specific and do not extend outside their containing `Document`. I'll try to make that clear.

**Comment by MattMenke2** [comment]
Thanks for the followup!  I admit my DOM-foo is pretty weak, so spec may be clear to those with more familiarity with the web platform.  I'll go ahead and mark this as approved, from a privacy standpoint.
