### ISSUE TITLE
Should app history survive tab discards & crashes?

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/history_api#17]
It'd be great if history state could survive:

- Tab discard
- Tab crash
- Browser restart

In cases where history state cannot be restored, maybe those history entries should be discarded altogether?

**Comment by domenic** [comment]
The intention is to behave similar to `history.state` in this regard. I believe `history.state` survives browser restart and tab discard, but I'm not sure about crashes. And, the answer might be browser-specific.

So, maybe this is just something we could tighten up generally, for both `history.state` and app history state.

**Comment by domenic** [comment]
Moved to https://github.com/WICG/app-history/issues/2!
