### ISSUE TITLE
Navigation through the app history list: Shouldn't there be more failure cases and reasoning?

### ISSUE THREAD

**Issue by SetTrend** [slightlyoff/history_api#19]
At https://github.com/slightlyoff/history_api/blob/master/app_history.md#navigation-through-the-app-history-list it reads (harshly abbreviated to make my point):

> 1. Navigate event handler fails →
>    - promise **rejects**
>    - `appHistory.currentEntry` stays the same.
> 1. Navigate event cancels →
>    - promise **fulfills with undefined**
>    - `appHistory.currentEntry` stays the same.
> 1. Not possible to navigate →
>    - promise **fulfills with undefined**
>    - `appHistory.currentEntry` stays the same.
> 1. The navigation succeeds, same-document →
>    - promise **fulfills with undefined**
>    - `appHistory.currentEntry` (as well as the URL bar, if appropriate) will update.
> 1. The navigation succeeds, different-document →
>    - promise will never settle
<br/>

- Shouldn't case 2 and 3 rather _reject_, like case 1?

- I suggest an enum value should give reason about the unsuccessful navigation for logging/debugging purposes.

- Shouldn't case 5 also mention:
   "`appHistory.currentEntry` (as well as the URL bar) will update."

**Comment by domenic** [comment]
> Shouldn't case 2 and 3 rather reject, like case 1?

I'm unsure, personally. I'm looking forward to discussing!

My thinking is that these cases aren't necessarily exceptional. Especially not being able to navigate backward or forward, per 3, is pretty common. And if your own application cancels a navigation, per 2, then you shouldn't get an error in the part of the code that initiated the navigation I think; that'd be annoying to have to `try`/`catch`.

What do you think? It'd be especially helpful if you had code examples, using e.g. `history.back()` or some history/router library, so we could see whether a (part of a) real application would benefit from a rejection in these situations.

> I suggest an enum value should give reason about the unsuccessful navigation for logging/debugging purposes.

This is an interesting idea; let's definitely keep it in mind!

> Shouldn't case 5 also mention: "appHistory.currentEntry (as well as the URL bar) will update."

The URL bar will indeed update. But `appHistory.currentEntry` won't update, because the entire `appHistory` object will be gone, along with the `Document`. There will be a new, separate `appHistory` object, but there's no sense in which the old one had its entry updated.

**Comment by SetTrend** [comment]
> the code that initiated the navigation I think; that'd be annoying to have to `try`/`catch`.

I see ... when you're writing "reject", I believed you were mentioning promise rejections? So, you mean a different thing then?

I know, it is much to ask, but would you mind providing brief pseudo code samples along with the text to eliminate room for interpretation?

If "reject" and "fullfill" would have been promise handlers, then I believe code for navigation _failure/cancellation/error_ to be rather similar and in much contrast to code for navigation _success_.
<br/>

> > I suggest an enum value should give reason about the unsuccessful navigation for logging/debugging purposes.
> 
> This is an interesting idea; let's definitely keep it in mind!

Marvellous!
<br/>

> > Shouldn't case 5 also mention: "appHistory.currentEntry (as well as the URL bar) will update."
> 
> The URL bar will indeed update. But `appHistory.currentEntry` won't update, because the entire `appHistory` object will be gone, along with the `Document`. There will be a new, separate `appHistory` object, but there's no sense in which the old one had its entry updated.

I see. Thank you for clarifying. I guess, that's more or less the information I was missing in (and suggesting to add to) case 5.

**Comment by domenic** [comment]
> I see ... when you're writing "reject", I believed you were mentioning promise rejections? So, you mean a different thing then?

I'm not sure which instance of me writing "reject" you're referring to, but in general, I use "reject" for promises, and "cancel" for navigations. Canceling a navigation is, IMO, not exceptional (and promise rejections corresond to sync exceptions; see https://www.w3.org/2001/tag/doc/promises-guide#rejections-should-be-exceptional).

> I know, it is much to ask, but would you mind providing brief pseudo code samples along with the text to eliminate room for interpretation?

For sure. Here's an instance of case 2:

```js
appHistory.addEventListener("navigate", e => {
  // Cancel the navigation and instead do a SPA nav
  e.respondWith(doSinglePageNav(e.currentEntry);
});

// Initiate the navigation. It will go through the navigate event handler above.
const promise = appHistory.pushNewEntry({ url: "/foo" });
```

Should `promise` be rejected? IMO no. It would be annoying to have to write

```js
try {
  await appHistory.pushNewEntry({ url: "/foo" });
} catch {
  // Do nothing because we expect this navigation to be intercepted and canceled and converted to a SPA nav.
}
```

> I guess, that's more or less the information I was missing in (and suggesting to add to) case 5.

Will do!

**Comment by SetTrend** [comment]
Ah, I see .. So "cancelling" to this regard refers to cancelling the navigation from within the `navigate` event handler, not by the user clicking the "cancel navigation" button on his/her browser. 👍 

Yet, case 3 still seems a rather exceptional situation to me.

And, yes, you're right. I'm a bit behind the latest in JavaScript. Pardon me for this inconvenience. I'm very much interested in your proposal and want to have it ASAP. That's why I'm so interested in reading through your spec.

**Comment by domenic** [comment]
I've filed https://github.com/WICG/app-history/issues/16 for discussing case (3) further; let's move the discussion there!
