### ISSUE TITLE
Navigation monitoring and interception: exchange "DOM element" for "DOM Node"

### ISSUE THREAD

**Issue by SetTrend** [slightlyoff/history_api#20]
At https://github.com/slightlyoff/history_api/blob/master/app_history.md#navigation-monitoring-and-interception it reads:

>`fragmentTarget`: a DOM element or null, indicating the target of the current navigation, if the current navigation is a same-document fragment navigation or scroll to text fragment navigation. _TODO I don't this works for scroll to text fragment, which uses ranges, not elements. Maybe make this just a boolean._

I propose to exchange "DOM element" for "DOM Node". Then everything will work out.

**Comment by domenic** [comment]
I'm not so sure. [Ranges](https://dom.spec.whatwg.org/#ranges), used by scroll-to-text-fragment, are not nodes.

**Comment by SetTrend** [comment]
D'oh, my mistake.

I didn't know these existed. URL Text Fragments have not been added to the standard yet, have they?

**Comment by domenic** [comment]
Right, they have a specification and are shipping in Chrome, but have not yet been moved into the HTML Standard. https://github.com/WICG/scroll-to-text-fragment
