### ISSUE TITLE
Wouln't it be beneficial to be able to update AppHistoryEntry from within navigate instead of raising a second navigation?

### ISSUE THREAD

**Issue by SetTrend** [slightlyoff/history_api#23]
In some of the examples (e.g. [Example: single-page app "redirects"](https://github.com/slightlyoff/history_api/blob/master/app_history.md#example-single-page-app-redirects) a navigation is cancelled and a second navigation is launched.

Wouldn't it be beneficial to be able to just update the `AppHistoryEntry` member of the event object directly from within the `navigate` event and to continue with the altered entry?

**Comment by domenic** [comment]
Yes! See the TODO in https://github.com/slightlyoff/history_api/blob/master/app_history.md#example-affiliate-links

> TODO: it feels like this should be less disruptive than a cancel-and-perform-new-navigation; it's just a tweak to the outgoing navigation. Using the same code as the previous example feels wrong. Some brainstorming needed.

I'm just unsure what the API should look like.

Maybe

```js
e.respondWith({ url });
```

?

**Comment by SetTrend** [comment]
Would it be wrong to edit the entry directly and write something like:

```js
appHistory.addEventListener("navigate", e => {
  if (e.destinationEntry.url.hostname === "store.example.com") {
    e.destinationEntry.url.queryParams.set("affiliateId", "ead21623-781e-442f-a2c4-6cc1b2a9fda2");
  }
});
```

**Comment by domenic** [comment]
Well, `url` is a string, not a URL object (see https://url.spec.whatwg.org/#url-apis-elsewhere), so it'd be more like

```js
appHistory.addEventListener("navigate", e => {
  const url = new URL(e.destinationEntry.url);
  if (url.hostname === "store.example.com") {
    url.queryParams.set("affiliateId", "ead21623-781e-442f-a2c4-6cc1b2a9fda2");

    e.destinationEntry.url = url; // implicit toString conversion
  }
});
```

And, that would mean we'd need to make `destinationEntry` not be an `AppHistoryEntry`, but instead some sort of `PotentialAppHistoryEntry`, because other `AppHistoryEntry`s are not mutable. (I don't mind making it a new type though; it's a bit of a special case.)

Hmm.

This is closely related to the mutability discussion in #21.

**Comment by SetTrend** [comment]
Absolutely. I commented in #21 on this.

**Comment by domenic** [comment]
Moved to https://github.com/WICG/app-history/issues/5!
