### ISSUE TITLE
Current entry change monitoring: It may be beneficial to be able to see the previous element

### ISSUE THREAD

**Issue by SetTrend** [slightlyoff/history_api#24]
At https://github.com/slightlyoff/history_api/blob/master/app_history.md#current-entry-change-monitoring the `currententrychange` is introduced.

It may be beneficial to have the `e` event parameter provide a member pointing to the previously active app history entry.

This might also obsolete [Per-entry events](https://github.com/slightlyoff/history_api/blob/master/app_history.md#per-entry-events).

**Comment by domenic** [comment]
I can totally believe it would be useful. Do you have an example use case, that we could turn into something to put in the explainer? As you can see, the examples for that section are sparser than I would like.

> This might also obsolete Per-entry events.

From what I've heard from other folks per-entry events still have their use cases, for individual components of the type shown there. There's probably some overlap, but my preference is to keep both until we've got some evidence that they're 100% redundant.

**Comment by SetTrend** [comment]
Sure:

It may be beneficial if, for instance, the `state` for each of the entries differed. From within the `currententrychange` event, texts in the frame could be calculated with the differential result.

```js
appHistory.addEventListener("currententrychange", e =>
{
  let diff = e.currentEntry.state.listItems.length - e.previousEntry.state.listItems.length;

  document.getElementById("result").innerText = `${Math.Abs(diff)} items have been ${diff < 0 ? "removed" : "added"}`;
});
```

> From what I've heard from other folks per-entry events still have their use cases, for individual components of the type shown there.

Absolutely! I'm just throwing my thoughts into the ring in case they may be beneficial or ring a bell.

**Comment by domenic** [comment]
Moved to https://github.com/WICG/app-history/issues/14!
