### ISSUE TITLE
How can the current position in appHistory.entries be determined?

### ISSUE THREAD

**Issue by SetTrend** [slightlyoff/history_api#25]
In order to be able to enable "Back" and "Forward" buttons, it would be necessary to observe where in the `appHistory.entries` list a frame currently is.

At the beginning `appHistory.entries` is empty (or null?). Testing for being first or last element in the list could become tedious then. Are there properties to query for being able to move backward/forward? (E.g. `CanGoBack`/?`CanGoForward`)

**Comment by domenic** [comment]
>  it would be necessary to observe where in the appHistory.entries list a frame currently is.

You could do this with `appHistory.entries.indexOf(appHistory.currentEntry)`

> At the beginning appHistory.entries is empty (or null?)

No, it'll always contain the current entry, so it'll be of length 1.

> Are there properties to query for being able to move backward/forward? (E.g. CanGoBack/?CanGoForward)

This seems like reasonable sugar to add, for `appHistory.entries.indexOf(appHistory.currentEntry) === 0` and `appHistory.entries.indexOf(appHistory.currentEntry) === appHistory.entries.length - 1`. Do you have examples, preferably from a real app, of how this would be used?

**Comment by SetTrend** [comment]
Sure: Within an `iframe`, browser buttons won't necessarily apply. So, if you want to go through form input's revisions when the form is put within an `iframe`, navigation buttons within the `iframe` would be required.

**Comment by domenic** [comment]
Moved to https://github.com/WICG/app-history/issues/6!
