### ISSUE TITLE
`fragmentTarget` should probably be renamed to `fragmentDirective`

### ISSUE THREAD

**Issue by tomayac** [slightlyoff/history_api#28]
In Text Fragments URLs, it's called `fragmentDirective` and is located on `document` (see https://github.com/WICG/scroll-to-text-fragment/issues/130 and the [draft spec](https://wicg.github.io/scroll-to-text-fragment/#feature-detectability)). Should this proposal align on the same naming?

Note: we're planning on adding support for more than just `#:~:text` in the future, namely `#:~:selector` (see the [Explainer](https://github.com/WICG/scroll-to-text-fragment/blob/master/EXTENSIONS.md) for details. (CC: @flackr @grantjwang)

**Comment by domenic** [comment]
I think it's probably going to have to switch to just a boolean, maybe `fragment`. It's meant to encompass any change in the fragment, whether it's scroll-to-fragment, scroll-to-text-fragment, or future things, and we can't guarantee those will always be nodes.

**Comment by domenic** [comment]
Let's track this in https://github.com/WICG/app-history/issues/4!
