### ISSUE TITLE
question: action completion back vs forward

### ISSUE THREAD

**Issue by matt-buland-sfdc** [slightlyoff/history_api#29]
Something I've struggled with is history maintenance for pages that temporarily have a history entry, and I'm curious on your thoughts, and how to bridge this experience with the history API (though ultimately, this may just be a user-space problem).

Consider a CRUD app:
I start at `/tasks`, I click a link that pushes an entry to `/tasks/new`, where I fill out a form (note: this could be implemented as a modal or a page, though the problem statement remains the same). Cancelling this form has a clear path: `appHistory.back();` -- but how should we handle the success case?
- `appHistory.pushNewEntry(url: '/tasks')` -- this visually appears to work, but now the back-button is unintuitive: back -> `/tasks/new` -> `/tasks` (again)
- `appHistory.back()` -- this only works if the intended destination is the previous page (not an appropriate assumption)
- `appHistory.back(); appHistory.updateCurrentEntry();` -- this fixes the history, but causes many navigation events, which may _start_ rendering the previous page, only to immediately tear it down, leading to rendering inefficiencies, and view flickering in the worst case (renderer dependent). Our app also has side-effects to push vs pop navigation which makes this a bigger struggle: historical navigation allows the page to use cached information or content that is stale in the DOM, but push navigation tries to fetch the latest, and will generally freshly render the page. So really, the ideal would be to use `back(); back(); pushNewEntry();` so that it's clear it should be treated like a push, but the history gets cleaned up.
- proposed new API: `appHistory.pushEntryFrom(key, {url: '/tasks'})` -- the goals of this API would be: limit the events to only 1 navigate/currententrychange event, the history entries after `key` are discarded, and the navigate/change is indistinguishable from a pushNavigation (including the lack of common back/historical indicators like popstate).

I realize this may be an application specific problem that could be solved with our own navigation API that intercepts and conditionally ignores some of the events in this scenario, but it also feels like a general problem that applications may be leaving unsolved at the expense of either unnecessary rendering work or mangled browser history. Any thoughts or suggestions?

**Comment by domenic** [comment]
Thanks for filing this! I'm very interested in exploring these sorts of problems. This kind of reminds me of https://mobile.twitter.com/juandopazo/status/1356689596805836802, which I've tried to capture in https://github.com/WICG/app-history/issues/9.

> appHistory.pushNewEntry(url: '/tasks') -- this visually appears to work, but now the back-button is unintuitive: back -> /tasks/new -> /tasks (again)

This is what I'd expect as a user; if you click back you get back to what you were seeing previously. And if you click back again, you get back to what you were seeing before that.

It's not clear what desired user experience you're looking for. It sounds like it's something else?

Let me close this as we're trying to consolidate issues into https://github.com/WICG/app-history/issues, but I'm happy to either continue discussing in the closed thread, or have you open a new issue over there to get into the use case further.

**Comment by matt-buland-sfdc** [comment]
Opened this issue in the new repo. I reformulated the problem statement a bit to try to be more clear, and demonstrated the difference between https://github.com/WICG/app-history/issues/9

new issue: https://github.com/WICG/app-history/issues/21
