### ISSUE TITLE
intercepting cross-origin requests needs clear use-cases

### ISSUE THREAD

**Issue by matt-buland-sfdc** [slightlyoff/history_api#32]
A major use-case I could see for intercepting cross-origin is to show or redirect to some "you're leaving this site, are you sure" banner. But in order to eventually let the user actually leave, there needs to be an exit condition, like: `currentEntry.url.startsWith("/redirectnotice")`, though I suspect that it may be counter-intuitive for apps to do this. Clear guidance or recipes on what cross-origin navigations could be used for would help.

**Comment by domenic** [comment]
Is https://github.com/slightlyoff/history_api/blob/master/app_history.md#example-affiliate-links not convincing? Or any of the other many cases where sites do URL rewriting today?

**Comment by matt-buland-sfdc** [comment]
I think I'm just mirroring the TODO comment. I agree that interception like adding an affiliate link or showing an interstitial redirect page can be disruptive, but that may also be the nature of the feature.

I think the affiliate links example is convincing enough, maybe just tweak the heading or description to make it include the "cross-origin" key-word so it can be searched for and associated with that property. Following that, would the example want to (redundantly) check for `!e.sameOrigin` before applying the affiliate link?

**Comment by domenic** [comment]
I added "cross-origin" to the heading, and we can track the TODO in https://github.com/WICG/app-history/issues/5!
