### ISSUE TITLE
ModalCloseWatcher should allow some associated data

### ISSUE THREAD

**Issue by tabatkins** [slightlyoff/history_api#35]
Currently ModelCloseWatcher has a no-arg constructor, and the `close` event fires with no significant information on the Event object.

In most cases, including all the examples given in the explainer, however, the ModalCloseWatcher is created to allow closing a *specific* element on the page. This means you have to create a fresh arrow function every time you create a ModalCloseWatcher so you can act on the desired element.

It would be useful if you could pass this element (or potentially any other useful data) to ModalCloseWatcher in the constructor, and have it handed back to you on the `close` event, so you can write a generic modal-closer function and reuse it across multiple ModalCloseWatchers.

**Comment by domenic** [comment]
I'm not sure this pulls its weight. It seems like you're asking for the ability to write

```js
const watcher1 = new ModalCloseWatcher(data1);
watcher1.onclose = closeHandler;

const watcher2 = new ModalCloseWatcher(data2);
watcher2.onclose = closeHandler;
```

instead of 

```js
const watcher1 = new ModalCloseWatcher();
watcher1.onclose = () => closeHandler(data1);

const watcher2 = new ModalCloseWatcher();
watcher2.onclose = () => closeHandler(data2);
```

which doesn't seem like a big win, as it introduces an API-specific way of closing over data instead of using the generic JavaScript langauge feature (closures).

**Comment by tabatkins** [comment]
That's a reasonable counter.
