### ISSUE TITLE
Easier same-origin back navigation

### ISSUE THREAD

**Issue by RichardLindhout** [slightlyoff/history_api#6]
I think I see some improvement to check which pages are visited in the history (if it's the same origin which would probably fix the issue described below too in an easier way)

Ideally there would be a way to provide a fallback on the history.back() function which could could trigger if the user would go back to another website. Like the in-app back button on Android devices.

So if user comes from Google to products/1
The in website button should return to products

But if the user comes from inside the website (e.g. via the Cart page) the user should go back to the Cart.

In websites I did solve this problem in a 'hacky' way (I don't know if this works in all browser)

```html
<script>
	function goBack(e) {
		if (document.referrer.startsWith("<?php echo get_site_url(); ?>")) {
			e.preventDefault()
			history.back()
		}
	}
</script>
<a href="/products>" onclick="goBack(event)">Go Back</a>
```

It would be nice to have history.back('/product') which would only go the url if the previous url is not of the same origin

**Comment by RichardLindhout** [comment]
Btw the document.referrer is only filled on desktop Chrome and works only with server-side routing (I guess).

**Comment by tbondwilkinson** [comment]
Is this part of a wider discussion of how best to get information about the same-origin history stack before performing a navigation? Or is this more wanting to respond to a history navigation with extra information from the history stack?

I think in both cases, we're still discussing whether or not the history stack (same-origin) should be readable, but I strongly think it should be.

**Comment by tbondwilkinson** [comment]
Specifically, see this section to point out where your use case couldn't be solved with the current proposal:

https://github.com/slightlyoff/history_api#same-origin-history-stack-introspection

**Comment by RichardLindhout** [comment]
I think that api would fix it! I hope something like it will be implemented soon. This is one of the reasons why I would need this api to fix a UX issue.

However maybe we could provide the goBackOrUrl('/products') as easier alternative to this code. But to be honest I think the current api is pretty straightforward!
```
let previousRoutes = history.states()
if (previousRoutes.length > 0) {
history.push('/product')
} else {
history.goBack()
}
```

**Comment by matt-buland-sfdc** [comment]
Seems like this has been resolved. Do you plan to close solved issues?
